### ISSUE TITLE
这个是关键点是多少个的？

### ISSUE THREAD

**Issue by Andrawzyf** [zhacheny/Head-Pose-Estimation-using-opencv-by-C-#1]

**Comment by zhacheny** [comment]
你好请问你说的是landmark么 我这里用了5个 但是其实是可以调整的 landmark越多精准度越高

**Comment by Andrawzyf** [comment]
@zhacheny 是的，调整？请教一下怎么调整呢？如果是68个呢？

**Comment by zhacheny** [comment]
不好意思啊最近工作比较忙回的晚，是这样的：找到这个函数
cv::solvePnP(model_points, image_points, camera_matrix,
			dist_coeffs, rotation_vector, translation_vector, false, SOLVEPNP_UPNP);
model_points就是模板矩阵，image_points就是你的输入矩阵。

**Comment by Andrawzyf** [comment]
@zhacheny 看到了，学习了

**Comment by zhacheny** [comment]
不客气哦 那我close了
